server:
  port: 8100
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.hello.provider.user: ERROR
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8050/eureka
    # 以便调式
    eureka-server-connect-timeout-seconds: 60
    eureka-server-read-timeout-seconds: 60
  instance:
    prefer-ip-address: true